
services:
  db:
    image: mysql:8.0-debian
    container_name: db
    restart: always
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD

    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - internal-network

  wordpress:
    depends_on:
      - db
    image: wordpress:6.7.1-fpm-alpine
    container_name: wordpress
    restart: always
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - internal-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.27.3-alpine
    container_name: webserver
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      - internal-network

  # certbot:
  #   depends_on:
  #     - webserver
  #   image: certbot/certbot
  #   container_name: certbot
  #   ports:
  #     - 80:80
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - wordpress:/var/www/html
  #   command: certonly --standalone --email mail@mail.com --agree-tos --no-eff-email --force-renewal -d srv684.mysnp.ir 
  
  pma:
    depends_on:
       - db
    image: phpmyadmin/phpmyadmin:5.2
    container_name: pma
    restart: always
    networks:
      - internal-network
    expose:
      - "80"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_HOST=db
      - PMA_ARBITRARY=1
      - PMA_PORT=3306

volumes:
  certbot-etc:
  wordpress:
  dbdata:

networks:
  internal-network:
    name: internal-network
    driver: bridge