apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: scenario2
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 30090
    hostPort: 8090
    listenAddress: "0.0.0.0"
    protocol: TCP
- role: worker
- role: worker
