apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: storage
spec:
  selector:
    matchLabels:
      app: nfs-server
  replicas: 1
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: itsthenetwork/nfs-server-alpine:latest
        ports:
        - name: nfs
          containerPort: 2049
        securityContext:
          privileged: true
        env:
        - name: SHARED_DIRECTORY
          value: "/nfsshare" # Set the shared directory
        volumeMounts:
        - name: storage
          mountPath: /nfsshare # Must match SHARED_DIRECTORY
      volumes:
      - name: storage
        hostPath:
          path: /data/nfs # Path on the host node
          type: DirectoryOrCreate

