apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:17.7.0-ce.0
          
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 22
          
          volumeMounts:
            - name: gitlab-data
              mountPath: /var/www/html
          
          env:
            - name: GITLAB_ROOT_PASSWORD
              value: F/Wwc48pwAwzhrEavQy5w0VeX60EPgb+JQVqngx0hsA=
   
          resources:
            limits:
              memory: 2048Mi
              cpu: "2"
            requests:
              memory: 512Mi
              cpu: "0.5"

      volumes:
        - name: gitlab-data
          persistentVolumeClaim:
            claimName: gitlab-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: gitlab-service
spec:
  type: NodePort
  selector:
    app: gitlab
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30090

    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30443

    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30022


  