apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    type: gitlab-nfs # Added label to match the PVC selector
spec:
  capacity:
    storage: 6Gi # Adjust the storage size as per your requirement
  accessModes:
    - ReadWriteMany
  nfs:
    path: /
    server: 172.20.110.100 # IP of your NFS server
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pvc
spec:
  accessModes:
  - ReadWriteMany # Matches the PV's access mode
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
  selector:
    matchLabels:
      type: gitlab-nfs # Matches the PV label

