apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:php8.3-apache
          
          ports:
            - containerPort: 80
              name: wordpress
          
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html
          
          env:
            - name: WORDPRESS_DB_HOST
              value: 91.107.179.216:3306
            - name: WORDPRESS_DB_PASSWORD
              value: 5sad4f54sdaf65sdf465sdaf6fsdeeee
            - name: WORDPRESS_DB_USER
              value: wpuser
            - name: WORDPRESS_DB_NAME
              value: wordpress                   
                          
          resources:
            limits:
              memory: 2048Mi
              cpu: "2"
            requests:
              memory: 256Mi
              cpu: "0.2"

      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: wordpress-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: wordpress-service
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000


